fail-on-severity: moderate

comment-summary-in-pr: always

allow-licenses:
  - MIT
  - GPL-3.0
  - BSD-3-Clause

fail-on-scopes:
  - development
  - runtime
  - unknown

security-checks:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        config-file: >-
          ./.github/dependency-review-config.yml
